### ISSUE TITLE
An error occurs when launching the benchmark.

### ISSUE THREAD

**Issue by shiwk** [awslabs/s3-connector-for-pytorch#166]
`RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

The issue arises when running the benchmark code for the Vision Transformer (VIT). I believe it occurs because the input tensor is located on the CPU, while the model is on the GPU.

It will work with the addition of a single line of code:
`model = self.model.to(self.device)`

**Comment by IsaevIlya** [comment]
Hello @shiwk,
Thank you for letting us know about the issue. We will have a look on it. Meanwhile, could you share the instance type on which you faced that issue?

**Comment by shiwk** [comment]
> Hello @shiwk, Thank you for letting us know about the issue. We will have a look on it. Meanwhile, could you share the instance type on which you faced that issue?

Hi @IsaevIlya , I run it on my own server with a GPU, not on any service of AWS

**Comment by IsaevIlya** [comment]
@shiwk, Thank you for bringing up this issue. I've successfully replicated it, and the resolution should be addressed by the  PR https://github.com/awslabs/s3-connector-for-pytorch/pull/172
