### ISSUE TITLE
S3MapDataset hangs forever

### ISSUE THREAD

**Issue by TommasoBendinelli** [awslabs/s3-connector-for-pytorch#167]
### s3torchconnector version

 1.1.4

### s3torchconnectorclient version

 1.1.4

### AWS Region

us-east-1

### Describe the running environment

"trn1.2xlarge" with "ami-09765a839c76c84f2",

### What happened?

This code hangs forever, i.e. the map_dataset[0] does not return

```
from s3torchconnector import S3MapDataset, S3IterableDataset

# You need to update <BUCKET> and <PREFIX>
DATASET_URI="s3://my_data/"
REGION = "us-east-1"


def main():
  map_dataset = S3MapDataset.from_prefix(DATASET_URI, region=REGION)
  
  # This blocks forever
  object = map_dataset[0]
```

The weird thing that this works just fine

```
from s3torchconnector import S3MapDataset, S3IterableDataset

# You need to update <BUCKET> and <PREFIX>
DATASET_URI="s3://my_data/"
REGION = "us-east-1"


def main():

  iterable_dataset = S3IterableDataset.from_prefix(DATASET_URI, region=REGION)

  # This works
  for object in iterable_dataset:
    print(object.key)

if __name__ == "__main__":
  main()

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IsaevIlya** [comment]
Hello @TommasoBendinelli,
Thank you for bringing the issue to our attention. Could you please provide the count of objects under the `DATASET_URI` you are using? It will help us to reproduce the issue.

**Comment by TommasoBendinelli** [comment]
Around 5M objects. By the way if I do len(map_dataset) it's also blocking.

**Comment by IsaevIlya** [comment]
Would you please run your script with logging  enabled? `S3MapDataset` eagerly lists all the objects under the given prefix. This process might take some time and may give the impression of being unresponsive. Logs should show if the application is hanging or is processing list requests.

To enable logging add the following lines at the top of your script:

```py
from s3torchconnectorclient import LOG_TRACE
logging.basicConfig(
    format="%(levelname)s %(name)s %(asctime)-15s %(filename)s:%(lineno)d %(message)s"
)
logging.getLogger().setLevel(LOG_TRACE)
```

**Comment by TommasoBendinelli** [comment]
Indeed I get some output (here a snippet)
```
DEBUG s3torchconnector._s3client._s3client 2024-03-05 14:45:38,293 _s3client.py:63 GetObject s3://poleno-2-dinoextracted/00676e6b5da5225e4f37575cd36af786, object_info is None=False
00676e6b5da5225e4f37575cd36af786
DEBUG s3torchconnector._s3client._s3client 2024-03-05 14:45:38,293 _s3client.py:63 GetObject s3://poleno-2-dinoextracted/00676ee473e869be88ecc94aeff89c92, object_info is None=False
00676ee473e869be88ecc94aeff89c92
DEBUG s3torchconnector._s3client._s3client 2024-03-05 14:45:38,293 _s3client.py:63 GetObject s3://poleno-2-dinoextracted/00676fa7a1d27a35265aba09d6228f6f, object_info is None=False
```
But how should I use the S3MapDataset in the __getitem__ method of Pytorch Dataset if it's indexing? Is it only one time thing?

**Comment by IsaevIlya** [comment]
Could you confirm that provided snipped is for `S3MapDataset`? At the logs beginning should be record like follow one:
```
INFO s3torchconnector.s3map_dataset 2024-03-05 15:34:15,108 s3map_dataset.py:111 Building S3MapDataset from_prefix s3_uri='s3://bucket/prefix/`
```  
The snippet that you provide contains a few `GetObject` requests. Based on the script that you provided initially, my expectation is that logs would contain only one `GetObject` request at the end and many`list_object` in the middle. Would you provide the entire log? 

`S3MapDataset` lists all the objects under the given prefix only once per instance. When the listing operation is finished, you can access any object by its index.

**Comment by TommasoBendinelli** [comment]
I just gave a snippet of the entire log because the total one was quite long (it prints many line per sec, for some minutes before finishing). I can confirm that it eventually finishes and it finishe I can access any element by its index.

I think we can close this issue as there is no bug, just a mis-understanding. To clear out things a bit I would mention it in the main README that S3MapDataset can take a while for the first index. Thanks a lot for the support!
