### ISSUE TITLE
Improve performance for loading checkpoints

### ISSUE THREAD

**Issue by IsaevIlya** [awslabs/s3-connector-for-pytorch#199]
### Tell us more about this new feature.

Hello,
There is the difference in performance for storing and loading "big" checkpoints (~20Gb), while using s3-connector-for-pytorch and PyTorch. When saving and loading 17.4Gb checkpoint on g5.12xlarge instance in us-west-2 region the time needed for upload is ~17 seconds, but time for load is ~30 seconds. Is it possible to improve loading time?
Bellow is the script that was used for measuring time:

```py
import torch
import uuid
import boto3
import s3torchconnector
import time
from transformers import AutoModelForMaskedLM

print("Start")

# 270mb model
model = AutoModelForMaskedLM.from_pretrained("distilbert/distilbert-base-uncased")
print("Loaded model")

# Increase the embedding size
model.resize_token_embeddings(6000000)
print("Resized model")

checkpoint_bucket = f"checkpoint-test{uuid.uuid4()}"
checkpoint_file = "test.chkpt"
checkpoint_path = f"s3://{checkpoint_bucket}/{checkpoint_file}"
region = "us-west-2"

# create bucket in the same region, where you run script
s3_client = boto3.client('s3', region_name=region)
s3_client.create_bucket(Bucket=checkpoint_bucket, CreateBucketConfiguration={'LocationConstraint': region})
print(f"Bucket '{checkpoint_bucket}' created successfully.")

part_size = 8 * 1024 * 1024
throughput_target_gbps = 100

print(f"part size is {part_size} bytes")
print(f"throughput target is {throughput_target_gbps} gbps")

config = s3torchconnector.S3ClientConfig(part_size = part_size, throughput_target_gbps=throughput_target_gbps)
s3checkpoint = s3torchconnector.S3Checkpoint(region=region, s3client_config=config)
    
# Measure upload time
t1 = time.time()
with s3checkpoint.writer(checkpoint_path) as writer:
    torch.save(model.state_dict(), writer)
t2 = time.time()

# list files in bucket
response = s3_client.list_objects_v2(Bucket=checkpoint_bucket)
file_name = [obj['Key'] for obj in response['Contents']]
file_size = [obj['Size'] for obj in response['Contents']]
print(f"File in bucket '{checkpoint_bucket}': {file_name}, file size {file_size}")
print(f"upload time to {checkpoint_path} is  {t2 - t1}")

# load model from checkpoint
print(checkpoint_path)
loaded = None
t1 = time.time()
with s3checkpoint.reader(checkpoint_path) as reader:
    loaded = torch.load(reader)
t2 = time.time()
print(f"load time is {t2-t1}")

#clean up bucket
print(f"{checkpoint_bucket} - {checkpoint_file}")
s3_client.delete_object(Bucket=checkpoint_bucket, Key=checkpoint_file)
s3_client.delete_bucket(Bucket=checkpoint_bucket)
print(f"Bucket '{checkpoint_bucket}' deleted successfully.")
```

script output:

```
Start
Loaded model
Resized model
Bucket 'checkpoint-test1f891bdb-3a82-42e8-90a4-fa271995888b' created successfully.
part size is 8388608 bytes
throughput target is 100 gbps
File in bucket 'checkpoint-test1f891bdb-3a82-42e8-90a4-fa271995888b': ['test.chkpt'], file size [18630098292]
upload time to s3://checkpoint-test1f891bdb-3a82-42e8-90a4-fa271995888b/test.chkpt is  17.582385540008545
s3://checkpoint-test1f891bdb-3a82-42e8-90a4-fa271995888b/test.chkpt
load time is 28.36537194252014
checkpoint-test1f891bdb-3a82-42e8-90a4-fa271995888b - test.chkpt
Bucket 'checkpoint-test1f891bdb-3a82-42e8-90a4-fa271995888b' deleted successfully.
```

**Comment by shiwk** [comment]
Greate job!  have you assessed the time required for ckpt downloading as well as the time taken by the PyTorch component `torch.load`during the loading process?

**Comment by shiwk** [comment]
> Hi @shiwk , Yes, we've evaluated the time required for both downloading the checkpoint from S3 and the time taken by the `torch.load` during the loading process to de-serialise data. With the changes in s3torchconnector 1.2.3 we improved that time especially for a bigger files (~ 17Gb). Specifically, the load time for the script at the top on the same instance type decreased from 28.3 seconds to 16.2 seconds.
> 
> ```
> Start
> Loaded model
> Resized model
> Bucket 'checkpoint-test3abb97f7-09fa-4410-a167-8041eaa5adc1' created successfully.
> part size is 8388608 bytes
> throughput target is 100 gbps
> File in bucket 'checkpoint-test3abb97f7-09fa-4410-a167-8041eaa5adc1': ['test.chkpt'], file size [18630098292]
> upload time to s3://checkpoint-test3abb97f7-09fa-4410-a167-8041eaa5adc1/test.chkpt is  18.065913677215576
> s3://checkpoint-test3abb97f7-09fa-4410-a167-8041eaa5adc1/test.chkpt
> load time is 16.242187023162842
> checkpoint-test3abb97f7-09fa-4410-a167-8041eaa5adc1 - test.chkpt
> Bucket 'checkpoint-test3abb97f7-09fa-4410-a167-8041eaa5adc1' deleted successfully.
> ```

That's greate. Do you know the exact duration it takes to download the checkpoint in this `16.242187023162842` seconds
