### ISSUE TITLE
Allow disabling virtual-hosted-style addressing

### ISSUE THREAD

**Issue by DamienMatias** [awslabs/s3-connector-for-pytorch#208]
### Tell us more about this new feature.

Hello,

I was wondering if there was a way to force the usage of path style requests instead of the default [virtual-hosted-style addressing](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html) ?
This is actually possible with [mountpoint-s3](https://github.com/awslabs/mountpoint-s3) as you can see [here](https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#endpoints-and-aws-privatelink) in their documentation. 

> To disable virtual-hosted-style addressing, use the --force-path-style command-line flag to instead send requests to https://example.com/docexamplebucket/.

This would allow us using the [LakeFS S3 Gateway](https://docs.lakefs.io/understand/architecture.html#s3-gateway) and potentially other usages that leverage tools still built around the path style addressing. 

Thank you 🙏

**Comment by N-o-Z** [comment]
@DamienMatias Hi - lakeFS maintainer here 👋🏽 
As a WA for this issue you can configure `LAKEFS_GATEWAYS_S3_DOMAIN_NAME` to enable lakeFS to work with a virtual host

**Comment by devel4848** [comment]
I'am also interested in disabling virtual-hosted-style addressing. I would like to use S3 Connector for PyTorch with a S3-compatible Ceph storage that can not be configured for virtual-hosted-style addressing because of the DNS implication. Only path-style addressing can be used in our context.

**Comment by jamesbornholt** [comment]
The S3 client we use supports disabling virtual-hosted-style addressing [here](https://docs.rs/mountpoint-s3-client/latest/mountpoint_s3_client/config/struct.EndpointConfig.html#method.addressing_style), so I think this would just be a matter of plumbing through a new flag from the various constructors (`S3IterableDataset.from_prefix` and friends) to the Rust constructor [here](https://github.com/awslabs/s3-connector-for-pytorch/blob/3ec7f023723a189617ea1e5ab63a34e6310d2ed2/s3torchconnectorclient/rust/src/mountpoint_s3_client.rs#L70-L74), similar to #195. I'm not sure we're going to get to this in the short term, but we'd happily review a PR!

**Comment by dannycjones** [comment]
I'll reopen this as while its merged, there's no new release. This should be supported in the next published version!
