### ISSUE TITLE
Does the S3 Connector use Mountpoint-s3?

### ISSUE THREAD

**Issue by ekaynar** [awslabs/s3-connector-for-pytorch#216]
Does the S3 Connector use a mountpoint-s3 fuse base file client under the hood? I am a bit confused about what the mountpoint-s3 client is here. If that is the case, do we need to follow the same bucket/object naming rules as mountpoint-s3?

**Comment by fuatbasik** [comment]
Hi @ekaynar,
Thanks a lot for your interest in using S3 Connector for Pytorch.

S3 Connector for Pytorch use part of Mountpoint project under the hood. It does use the same s3-client as Mountpoint ([mountpoint-s3-client](https://github.com/awslabs/mountpoint-s3/tree/main/mountpoint-s3-client)) but does not use fuse-based file connector. Therefore, you do not have to follow any particular bucket/object naming rules specific to Mountpoint.

[Mountpoint-s3-client](https://github.com/awslabs/mountpoint-s3/tree/main/mountpoint-s3-client) is a re-usable, high-performance S3 client. By re-using it at S3 Connector for Pytorch we benefit from the same performance gains without needing to assume file system semantics.

When creating Pytorch datasets, you can choose either providing either an [S3URI as the prefix](https://awslabs.github.io/s3-connector-for-pytorch/autoapi/s3torchconnector/s3iterable_dataset/index.html#s3torchconnector.s3iterable_dataset.S3IterableDataset.from_prefix) or [a list of S3URIs](https://awslabs.github.io/s3-connector-for-pytorch/autoapi/s3torchconnector/s3iterable_dataset/index.html#s3torchconnector.s3iterable_dataset.S3IterableDataset.from_objects). When a prefix is provided S3 Connector for PyTorch will discover all S3 objects starting the that prefix automatically. When a list of S3URIs are given your dataset will contain objects contained in that list. 

Please let us know if this answers your question and if there is anything else we can do to help.

Fuat.

**Comment by ekaynar** [comment]
Thanks, Fuat for the help and clarification of the technical details. This information is really helpful!
